/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ControllerUsuario;
import Model.ModelUsuario;
import java.time.Clock;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Monet
 */
public class ViewUsuarioPerfil extends javax.swing.JFrame {
    ModelUsuario modelUsuario = new ModelUsuario();
    ArrayList<ModelUsuario> listaModelUsuario = new ArrayList<>();
    ControllerUsuario controllerUsuario = new ControllerUsuario();
    
    int tipo_conta;
    int cadastro_cidade;
    int cadastro_usuario;
    int cadastro_estiva;
    int cadastro_cliente;
    int cadastro_estoque;
    
    int cadastro_fornecedor;
    int cadastro_departamento;
    int cadastro_bairro;
    int cadastro_rua;
    int pagar_conta;
    int retirar_estoque;
    
    int relatorio_entrada_estoque;
    int relatorio_saida_estoque;
    int despesa;
    int relatorio_parcelamento;
    int relatorio_estoque;
    int relatorio_venda;
    
    int relatorio_turno;
    int relatorio_produto_maisVendidos;
    int relatorio_conta_paga;
    int cancelar_venda;
    int parcelar_venda;
    int dar_desconto;
    int fazer_sangria;
    int abandonar_venda;
    
    /**
     * Creates new form ViewUsuarioPerfil
     */
    public ViewUsuarioPerfil() {
        initComponents();
        listando();
        butaoEditar.setEnabled(false);
    }
private void listando(){
    listaModelUsuario = controllerUsuario.listaModelUsuarioController();
    DefaultTableModel modelo = (DefaultTableModel) tabela.getModel();
    modelo.setNumRows(0);
    int cont = listaModelUsuario.size();
    for(int i = 0 ; i < cont; i++){
    modelo.addRow(new Object[]{
    listaModelUsuario.get(i).getId(),
    listaModelUsuario.get(i).getNome(),
    listaModelUsuario.get(i).getTipo()
    });
    }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jRPagarContas = new javax.swing.JRadioButton();
        jRCadastroRuas = new javax.swing.JRadioButton();
        jRRestirarProdutosEstoque = new javax.swing.JRadioButton();
        jRCadastroCidade = new javax.swing.JRadioButton();
        jRRelatorioEntradaEstoque = new javax.swing.JRadioButton();
        jRCadastroTiposConta = new javax.swing.JRadioButton();
        jRRelatorioSaidaEstoque = new javax.swing.JRadioButton();
        jRDespesas = new javax.swing.JRadioButton();
        jRCadastroUsuario = new javax.swing.JRadioButton();
        jRRelatorioParcelamentos = new javax.swing.JRadioButton();
        jRCadastroProdutoEstiva = new javax.swing.JRadioButton();
        jRRelatorioEstoque = new javax.swing.JRadioButton();
        jRCadastroCliente = new javax.swing.JRadioButton();
        jRRelatorioVendas = new javax.swing.JRadioButton();
        jRCadastroProdutoEstoque = new javax.swing.JRadioButton();
        jRRelatorioTurno = new javax.swing.JRadioButton();
        jRCadastroFornecedor = new javax.swing.JRadioButton();
        jRRelatorioProdutosMaisVendidos = new javax.swing.JRadioButton();
        jRCadastroDepartamento = new javax.swing.JRadioButton();
        jRRelatorioContaPaga = new javax.swing.JRadioButton();
        jRCadastroBairros = new javax.swing.JRadioButton();
        tfLogin = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfSenha = new javax.swing.JPasswordField();
        butaocadastro = new javax.swing.JButton();
        butaoEditar = new javax.swing.JButton();
        butaExcluir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jRCancelarVendas = new javax.swing.JRadioButton();
        jRParcelarVendas = new javax.swing.JRadioButton();
        jRDarDesconto = new javax.swing.JRadioButton();
        jRFazerSangria = new javax.swing.JRadioButton();
        jRAbandonarVendas = new javax.swing.JRadioButton();
        tfId = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Nome", "Tipo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 109, 568, 184));

        jRPagarContas.setText("Pagar contas");
        jRPagarContas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRPagarContasActionPerformed(evt);
            }
        });
        jPanel1.add(jRPagarContas, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 324, -1, -1));

        jRCadastroRuas.setText("Cadastrar ruas");
        jRCadastroRuas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRCadastroRuasActionPerformed(evt);
            }
        });
        jPanel1.add(jRCadastroRuas, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 547, -1, -1));

        jRRestirarProdutosEstoque.setText("Retirar produtos/estoque");
        jRRestirarProdutosEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRRestirarProdutosEstoqueActionPerformed(evt);
            }
        });
        jPanel1.add(jRRestirarProdutosEstoque, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 347, -1, -1));

        jRCadastroCidade.setText("Cadastrar cidades");
        jRCadastroCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRCadastroCidadeActionPerformed(evt);
            }
        });
        jPanel1.add(jRCadastroCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 347, -1, -1));

        jRRelatorioEntradaEstoque.setText("Relatório da entrada/estoque");
        jRRelatorioEntradaEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRRelatorioEntradaEstoqueActionPerformed(evt);
            }
        });
        jPanel1.add(jRRelatorioEntradaEstoque, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 374, -1, -1));

        jRCadastroTiposConta.setText("Cadastrar tipos de contas");
        jRCadastroTiposConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRCadastroTiposContaActionPerformed(evt);
            }
        });
        jPanel1.add(jRCadastroTiposConta, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 324, -1, -1));

        jRRelatorioSaidaEstoque.setText("Relatório da saída/estoque");
        jRRelatorioSaidaEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRRelatorioSaidaEstoqueActionPerformed(evt);
            }
        });
        jPanel1.add(jRRelatorioSaidaEstoque, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 400, -1, -1));

        jRDespesas.setText("Despesas");
        jRDespesas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRDespesasMouseClicked(evt);
            }
        });
        jRDespesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRDespesasActionPerformed(evt);
            }
        });
        jPanel1.add(jRDespesas, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 426, -1, -1));

        jRCadastroUsuario.setText("Cadastrar usuários");
        jRCadastroUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRCadastroUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(jRCadastroUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 374, -1, -1));

        jRRelatorioParcelamentos.setText("Relatório dos parcelamentos");
        jRRelatorioParcelamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRRelatorioParcelamentosActionPerformed(evt);
            }
        });
        jPanel1.add(jRRelatorioParcelamentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 449, -1, -1));

        jRCadastroProdutoEstiva.setText("Cadastrar produtos/estivas");
        jRCadastroProdutoEstiva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRCadastroProdutoEstivaActionPerformed(evt);
            }
        });
        jPanel1.add(jRCadastroProdutoEstiva, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 400, -1, -1));

        jRRelatorioEstoque.setText("Relatório do estoque");
        jRRelatorioEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRRelatorioEstoqueActionPerformed(evt);
            }
        });
        jPanel1.add(jRRelatorioEstoque, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 475, -1, -1));

        jRCadastroCliente.setText("Cadastrar clientes");
        jRCadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRCadastroClienteActionPerformed(evt);
            }
        });
        jPanel1.add(jRCadastroCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 426, -1, -1));

        jRRelatorioVendas.setText("Relatório das vendas");
        jRRelatorioVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRRelatorioVendasActionPerformed(evt);
            }
        });
        jPanel1.add(jRRelatorioVendas, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 498, -1, -1));

        jRCadastroProdutoEstoque.setText("Cadastrar produtos/estoque");
        jRCadastroProdutoEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRCadastroProdutoEstoqueActionPerformed(evt);
            }
        });
        jPanel1.add(jRCadastroProdutoEstoque, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 449, -1, -1));

        jRRelatorioTurno.setText("Relatório dos turnos");
        jRRelatorioTurno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRRelatorioTurnoMouseClicked(evt);
            }
        });
        jRRelatorioTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRRelatorioTurnoActionPerformed(evt);
            }
        });
        jPanel1.add(jRRelatorioTurno, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 524, -1, -1));

        jRCadastroFornecedor.setText("Cadastrar fornecedor");
        jRCadastroFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRCadastroFornecedorActionPerformed(evt);
            }
        });
        jPanel1.add(jRCadastroFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 475, -1, -1));

        jRRelatorioProdutosMaisVendidos.setText("Relatório dos prod mais vendidos");
        jRRelatorioProdutosMaisVendidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRRelatorioProdutosMaisVendidosActionPerformed(evt);
            }
        });
        jPanel1.add(jRRelatorioProdutosMaisVendidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 547, -1, -1));

        jRCadastroDepartamento.setText("Cadastrar departamentos");
        jRCadastroDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRCadastroDepartamentoActionPerformed(evt);
            }
        });
        jPanel1.add(jRCadastroDepartamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 498, -1, -1));

        jRRelatorioContaPaga.setText("Relatórios das contas pagas");
        jRRelatorioContaPaga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRRelatorioContaPagaActionPerformed(evt);
            }
        });
        jPanel1.add(jRRelatorioContaPaga, new org.netbeans.lib.awtextra.AbsoluteConstraints(423, 324, -1, -1));

        jRCadastroBairros.setText("Cadastrar bairros");
        jRCadastroBairros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRCadastroBairrosActionPerformed(evt);
            }
        });
        jPanel1.add(jRCadastroBairros, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 524, -1, -1));
        jPanel1.add(tfLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 11, 116, -1));

        jLabel1.setText("Login:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 14, -1, -1));

        jLabel2.setText("Senha:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 14, -1, -1));
        jPanel1.add(tfSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 11, 117, -1));

        butaocadastro.setText("Cadastrar");
        butaocadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butaocadastroActionPerformed(evt);
            }
        });
        jPanel1.add(butaocadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 630, -1, -1));

        butaoEditar.setText("Alterar");
        butaoEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butaoEditarActionPerformed(evt);
            }
        });
        jPanel1.add(butaoEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 630, 76, -1));

        butaExcluir.setText("Excluir");
        butaExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butaExcluirActionPerformed(evt);
            }
        });
        jPanel1.add(butaExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 630, 89, -1));

        jLabel3.setText("Tipo:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(426, 14, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ADMINISTRADOR", "ESTOQUE", "VENDEDOR", " " }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 11, 134, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("PDV"));

        jRCancelarVendas.setText("Cancelar vendas");
        jRCancelarVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRCancelarVendasActionPerformed(evt);
            }
        });

        jRParcelarVendas.setText("Parcelar vendas");
        jRParcelarVendas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRParcelarVendasMouseClicked(evt);
            }
        });
        jRParcelarVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRParcelarVendasActionPerformed(evt);
            }
        });

        jRDarDesconto.setText("Dar desconto");
        jRDarDesconto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRDarDescontoActionPerformed(evt);
            }
        });

        jRFazerSangria.setText("Fazer sangria");
        jRFazerSangria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRFazerSangriaActionPerformed(evt);
            }
        });

        jRAbandonarVendas.setText("Abandonar venda");
        jRAbandonarVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRAbandonarVendasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRCancelarVendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRDarDesconto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRParcelarVendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRFazerSangria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRAbandonarVendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRCancelarVendas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRParcelarVendas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRDarDesconto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRFazerSangria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRAbandonarVendas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(423, 372, 171, 198));

        tfId.setText("ID");
        jPanel1.add(tfId, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 14, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRCadastroUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRCadastroUsuarioActionPerformed
    if(cadastro_usuario == 1)
    {
    cadastro_usuario = 0;
    }else{
    cadastro_usuario = 1;
    }
    }//GEN-LAST:event_jRCadastroUsuarioActionPerformed

    private void jRCadastroTiposContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRCadastroTiposContaActionPerformed
    if(tipo_conta == 1)
    {
    tipo_conta = 0;
    }else{
    tipo_conta = 1;    
    }
    }//GEN-LAST:event_jRCadastroTiposContaActionPerformed

    private void jRCadastroCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRCadastroCidadeActionPerformed

    if(cadastro_cidade == 1)
    {
    cadastro_cidade = 0;
    }else{
    cadastro_cidade = 1;    
    }
    }//GEN-LAST:event_jRCadastroCidadeActionPerformed

    private void jRCadastroProdutoEstivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRCadastroProdutoEstivaActionPerformed
   
    if(cadastro_estiva == 1)
    {
    cadastro_estiva = 0;
    }else{
    cadastro_estiva = 1;    
    }
    }//GEN-LAST:event_jRCadastroProdutoEstivaActionPerformed

    private void jRCadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRCadastroClienteActionPerformed
    
    if(cadastro_cliente == 1)
    {
    cadastro_cliente = 0;
    }else{
    cadastro_cliente = 1;    
    }
    }//GEN-LAST:event_jRCadastroClienteActionPerformed

    private void jRCadastroProdutoEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRCadastroProdutoEstoqueActionPerformed
    
    if(cadastro_estoque == 1)
    {
    cadastro_estoque = 0;
    }else{
    cadastro_estoque = 1;    
    }
    }//GEN-LAST:event_jRCadastroProdutoEstoqueActionPerformed

    private void jRCadastroFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRCadastroFornecedorActionPerformed
    
    if(cadastro_fornecedor == 1)
    {
    cadastro_fornecedor = 0;
    }else{
    cadastro_fornecedor = 1;    
    }
    }//GEN-LAST:event_jRCadastroFornecedorActionPerformed

    private void jRCadastroDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRCadastroDepartamentoActionPerformed
    
    if(cadastro_departamento == 1)
    {
    cadastro_departamento = 0;
    }else{
    cadastro_departamento = 1;    
    }
    }//GEN-LAST:event_jRCadastroDepartamentoActionPerformed

    private void jRCadastroBairrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRCadastroBairrosActionPerformed
    
    if(cadastro_bairro == 1)
    {
    cadastro_bairro = 0;
    }else{
    cadastro_bairro = 1;    
    }
    }//GEN-LAST:event_jRCadastroBairrosActionPerformed

    private void jRCadastroRuasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRCadastroRuasActionPerformed
    
    if(cadastro_rua == 1)
    {
    cadastro_rua = 0;
    }else{
    cadastro_rua = 1;    
    }
    }//GEN-LAST:event_jRCadastroRuasActionPerformed

    private void jRPagarContasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRPagarContasActionPerformed
    
    if(pagar_conta == 1)
    {
    pagar_conta = 0;
    }else{
    pagar_conta = 1;    
    }
    }//GEN-LAST:event_jRPagarContasActionPerformed

    private void jRRestirarProdutosEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRRestirarProdutosEstoqueActionPerformed
    
    if(retirar_estoque == 1)
    {
    retirar_estoque = 0;
    }else{
    retirar_estoque = 1;    
    }
    }//GEN-LAST:event_jRRestirarProdutosEstoqueActionPerformed

    private void jRRelatorioEntradaEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRRelatorioEntradaEstoqueActionPerformed
    
    if(relatorio_entrada_estoque == 1)
    {
    relatorio_entrada_estoque = 0;
    }else{
    relatorio_entrada_estoque = 1;    
    }
    }//GEN-LAST:event_jRRelatorioEntradaEstoqueActionPerformed

    private void jRRelatorioSaidaEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRRelatorioSaidaEstoqueActionPerformed
    
    if(relatorio_saida_estoque == 1)
    {
    relatorio_saida_estoque = 0;
    }else{
    relatorio_saida_estoque = 1;    
    }
    }//GEN-LAST:event_jRRelatorioSaidaEstoqueActionPerformed

    private void jRDespesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRDespesasActionPerformed
    
    if(despesa == 1)
    {
    despesa = 0;
    }else{
    despesa = 1;    
    }
    }//GEN-LAST:event_jRDespesasActionPerformed

    private void jRRelatorioParcelamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRRelatorioParcelamentosActionPerformed
    
    if(relatorio_parcelamento == 1)
    {
    relatorio_parcelamento = 0;
    }else{
    relatorio_parcelamento = 1;    
    }
    }//GEN-LAST:event_jRRelatorioParcelamentosActionPerformed

    private void jRRelatorioEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRRelatorioEstoqueActionPerformed
    
    if(relatorio_estoque == 1)
    {
    relatorio_estoque = 0;
    }else{
    relatorio_estoque = 1;    
    }
    }//GEN-LAST:event_jRRelatorioEstoqueActionPerformed

    private void jRRelatorioVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRRelatorioVendasActionPerformed
    
    if(relatorio_venda == 1)
    {
    relatorio_venda = 0;
    }else{
    relatorio_venda = 1;    
    }
    }//GEN-LAST:event_jRRelatorioVendasActionPerformed

    private void jRRelatorioTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRRelatorioTurnoActionPerformed
    
    if(relatorio_turno == 1)
    {
    relatorio_turno = 0;
    }else{
    relatorio_turno = 1;    
    }
    }//GEN-LAST:event_jRRelatorioTurnoActionPerformed

    private void jRRelatorioProdutosMaisVendidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRRelatorioProdutosMaisVendidosActionPerformed
    
    if(relatorio_produto_maisVendidos == 1)
    {
    relatorio_produto_maisVendidos = 0;
    }else{
    relatorio_produto_maisVendidos = 1;    
    }
    }//GEN-LAST:event_jRRelatorioProdutosMaisVendidosActionPerformed

    private void jRRelatorioContaPagaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRRelatorioContaPagaActionPerformed
    
    if(relatorio_conta_paga == 1)
    {
    relatorio_conta_paga = 0;
    }else{
    relatorio_conta_paga = 1;    
    }
    }//GEN-LAST:event_jRRelatorioContaPagaActionPerformed

    private void jRCancelarVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRCancelarVendasActionPerformed
    
    if(cancelar_venda == 1)
    {
    cancelar_venda = 0;
    }else{
    cancelar_venda = 1;    
    }
    }//GEN-LAST:event_jRCancelarVendasActionPerformed

    private void jRParcelarVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRParcelarVendasActionPerformed
    
    if(parcelar_venda == 1)
    {
    parcelar_venda = 0;
    }else{
    parcelar_venda = 1;    
    }
    }//GEN-LAST:event_jRParcelarVendasActionPerformed

    private void jRDarDescontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRDarDescontoActionPerformed
    
    if(dar_desconto == 1)
    {
    dar_desconto = 0;
    }else{
    dar_desconto = 1;    
    }
    }//GEN-LAST:event_jRDarDescontoActionPerformed

    private void jRFazerSangriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRFazerSangriaActionPerformed
    
    if(fazer_sangria == 1)
    {
    fazer_sangria = 0;
    }else{
    fazer_sangria = 1;    
    }
    }//GEN-LAST:event_jRFazerSangriaActionPerformed

    private void jRAbandonarVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRAbandonarVendasActionPerformed
   
    if(abandonar_venda == 1)
    {
    abandonar_venda = 0;
    }else{
    abandonar_venda = 1;    
    }
    }//GEN-LAST:event_jRAbandonarVendasActionPerformed

    private void butaocadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butaocadastroActionPerformed
    if(tfLogin.getText().equals("") || tfSenha.getText().equals("") || jComboBox1.getSelectedItem().equals("TIPO")){
    JOptionPane.showMessageDialog(this, "Os campos LOGING e SENHA são obrigatórios!");
    
    }else{
    modelUsuario.setNome(tfLogin.getText());
    modelUsuario.setSenha(tfSenha.getText());
    modelUsuario.setTipo(jComboBox1.getSelectedItem()+"");
    
    modelUsuario.setAbandonar_venda(abandonar_venda);
    modelUsuario.setCadastro_bairro(cadastro_bairro);
    modelUsuario.setCadastro_cidade(cadastro_cidade);
    modelUsuario.setCadastro_cliente(cadastro_cliente);
    modelUsuario.setCadastro_departamento(cadastro_departamento);
    modelUsuario.setCadastro_estivas(cadastro_estiva);
    modelUsuario.setCadastro_estoque(cadastro_estoque);
    modelUsuario.setCadastro_fornecedor(cadastro_fornecedor);
    modelUsuario.setCadastro_rua(cadastro_rua);
    modelUsuario.setCadastro_usuario(cadastro_usuario);
    modelUsuario.setCancelar_venda(cancelar_venda);
    modelUsuario.setDar_desconto(dar_desconto);
    modelUsuario.setDespesa(despesa);
    modelUsuario.setFazer_sangria(fazer_sangria);
    modelUsuario.setPagar_conta(pagar_conta);
    modelUsuario.setParcela_venda(parcelar_venda);
    modelUsuario.setRelatorio_conta_pagaga(relatorio_conta_paga);
    modelUsuario.setRelatorio_entrada_estoque(relatorio_entrada_estoque);
    modelUsuario.setRelatorio_estoque(relatorio_estoque);
    modelUsuario.setRelatorio_parcelamento(relatorio_parcelamento);
    modelUsuario.setRelatorio_produto_maisVendido(relatorio_produto_maisVendidos);
    modelUsuario.setRelatorio_saida_estoque(relatorio_saida_estoque);
    modelUsuario.setRelatorio_turno(relatorio_turno);
    modelUsuario.setRelatorio_venda(relatorio_venda);
    modelUsuario.setRetira_estoque(retirar_estoque);
    modelUsuario.setTipo_conta(tipo_conta);
    
    modelUsuario.setTipo(jComboBox1.getSelectedItem()+"");
    if(controllerUsuario.salvarUsuarioController(modelUsuario)>0){   
    JOptionPane.showMessageDialog(null, "Usuário salvo com sucesso!");
    listando();   
    limparCampos();
    dispose();
    } 
    }
    }//GEN-LAST:event_butaocadastroActionPerformed

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
    butaocadastro.setEnabled(false);
    butaoEditar.setEnabled(true);
    butaExcluir.setEnabled(true);
    
    
    int linha = tabela.getSelectedRow();
    int cod = (int) tabela.getValueAt(linha, 0);
    try {
    modelUsuario = controllerUsuario.retornarUsuarioController(cod);
    tfId.setText(String.valueOf(modelUsuario.getId()));
    tfLogin.setText(modelUsuario.getNome());
    tfSenha.setText(modelUsuario.getSenha());
    jComboBox1.setSelectedItem(modelUsuario.getTipo());
    
    if(modelUsuario.getAbandonar_venda() != 0)
    {
        jRAbandonarVendas.setSelected(true);
        abandonar_venda = 1;
    }else
    {
        jRAbandonarVendas.setSelected(false);
        abandonar_venda = 0;
    }
    
    if(modelUsuario.getCadastro_bairro() != 0)
    {
        cadastro_bairro = 1;
        jRCadastroBairros.setSelected(true);
    }else
    {
        jRCadastroBairros.setSelected(false);
        cadastro_bairro = 0;
    }
    
    if(modelUsuario.getCadastro_cidade() != 0)
    {
        cadastro_cidade = 1;
        jRCadastroCidade.setSelected(true);
    }else
    {
        cadastro_cidade = 0;
        jRCadastroCidade.setSelected(false);
    }
    
    if(modelUsuario.getCadastro_cliente() != 0)
    {
        jRCadastroCliente.setSelected(true);
        cadastro_cliente = 1;
    }else
    {
        cadastro_cliente = 0;
        jRCadastroCliente.setSelected(false);
    }
    
    if(modelUsuario.getCadastro_departamento() != 0)
    {
        jRCadastroDepartamento.setSelected(true);
        cadastro_departamento = 1;
    }else
    {
        cadastro_departamento = 0;
        jRCadastroDepartamento.setSelected(false);
    }
    
    if(modelUsuario.getCadastro_estivas() != 0)
    {
        jRCadastroProdutoEstiva.setSelected(true);
        cadastro_estiva = 1;
    }else
    {
        jRCadastroProdutoEstiva.setSelected(false);
        cadastro_estiva = 0;
    }
    
    if(modelUsuario.getCadastro_estoque() != 0)
    {
        jRCadastroProdutoEstoque.setSelected(true);
        cadastro_estoque = 1;
    }else
    {
        jRCadastroProdutoEstoque.setSelected(false);
        cadastro_estoque = 0;
    }
    
    if(modelUsuario.getCadastro_fornecedor() != 0)
    {
        cadastro_fornecedor = 1;
        jRCadastroFornecedor.setSelected(true);
    }else
    {
        cadastro_fornecedor = 0;
        jRCadastroFornecedor.setSelected(false);
    }
    
    if(modelUsuario.getCadastro_rua() != 0)
    {
        jRCadastroRuas.setSelected(true);
        cadastro_rua = 1;
    }else
    {
        jRCadastroRuas.setSelected(false);
        cadastro_rua = 0;
    }
    
    if(modelUsuario.getCadastro_usuario() != 0)
    {
        jRCadastroUsuario.setSelected(true);
        cadastro_usuario = 1;
    }else
    {
        jRCadastroUsuario.setSelected(false);
        cadastro_usuario = 0;
    }
    
    if(modelUsuario.getCancelar_venda() != 0)
    {
        jRCancelarVendas.setSelected(true);
        cancelar_venda = 1;
    }else
    {
        jRCancelarVendas.setSelected(false);
        cancelar_venda = 0;
    }
    
    if(modelUsuario.getDar_desconto() != 0)
    {
        jRDarDesconto.setSelected(true);
        dar_desconto = 1;
    }else
    {
        jRDarDesconto.setSelected(false);
        dar_desconto = 0;
    }
    
    if(modelUsuario.getDespesa() != 0)
    {
        jRDespesas.setSelected(true);
        despesa = 1;
    }else
    {
        jRDespesas.setSelected(false);
        despesa = 1;
    }
    
    if(modelUsuario.getFazer_sangria() != 0)
    {
        jRFazerSangria.setSelected(true);
        fazer_sangria = 1;
    }else
    {
        jRFazerSangria.setSelected(false);
        fazer_sangria = 0;
    }
    
    if(modelUsuario.getPagar_conta() != 0)
    {
        jRPagarContas.setSelected(true);
        pagar_conta = 1;
    }else
    {
        jRPagarContas.setSelected(false);
        pagar_conta = 0;
    }
    
    if(modelUsuario.getParcela_venda() != 0)
    {
        jRParcelarVendas.setSelected(true);
        parcelar_venda = 1;
    }else
    {
        jRParcelarVendas.setSelected(false);
        parcelar_venda = 0;
    }
    
    if(modelUsuario.getRelatorio_conta_pagaga() != 0)
    {
        jRRelatorioContaPaga.setSelected(true);
        relatorio_conta_paga = 1;
    }else
    {
        jRRelatorioContaPaga.setSelected(false);
        relatorio_conta_paga = 0;
    }
    
    if(modelUsuario.getRelatorio_entrada_estoque() != 0)
    {
        jRRelatorioEntradaEstoque.setSelected(true);
        relatorio_entrada_estoque = 1;
    }else
    {
        jRRelatorioEntradaEstoque.setSelected(false);
        relatorio_entrada_estoque = 0;
    }
    
    if(modelUsuario.getRelatorio_parcelamento() != 0)
    {
        jRRelatorioParcelamentos.setSelected(true);
        relatorio_parcelamento = 1;
    }else
    {
        jRRelatorioParcelamentos.setSelected(false);
        relatorio_parcelamento = 0;
    }
    
    if(modelUsuario.getRelatorio_produto_maisVendido() != 0)
    {
        jRRelatorioProdutosMaisVendidos.setSelected(true);
        relatorio_produto_maisVendidos = 1;
    }else
    {
        jRRelatorioProdutosMaisVendidos.setSelected(false);
        relatorio_produto_maisVendidos = 0;
    }
    
    if(modelUsuario.getRelatorio_saida_estoque() != 0)
    {
        jRRelatorioSaidaEstoque.setSelected(true);
        relatorio_saida_estoque = 1;
    }else
    {
        jRRelatorioSaidaEstoque.setSelected(false);
        relatorio_saida_estoque = 0;
    }
    
    if(modelUsuario.getRelatorio_turno() != 0)
    {
        jRRelatorioTurno.setSelected(true);
        relatorio_turno = 1;
    }else
    {
        jRRelatorioTurno.setSelected(false);
        relatorio_turno = 1;
    }
    
    if(modelUsuario.getRelatorio_venda() != 0)
    {
        relatorio_venda = 1;
        jRRelatorioVendas.setSelected(true);
    }else
    {
        jRRelatorioVendas.setSelected(false);
        relatorio_venda = 0;
    }
    
    if(modelUsuario.getRetira_estoque() != 0)
    {
        jRRestirarProdutosEstoque.setSelected(true);
        retirar_estoque = 1;
    }else
    {
        jRRestirarProdutosEstoque.setSelected(false);
        retirar_estoque = 0;
    }
    
    if(modelUsuario.getTipo_conta() != 0)
    {
        jRCadastroTiposConta.setSelected(true);
        tipo_conta = 1;
    }else
    {
         jRCadastroTiposConta.setSelected(false);
        tipo_conta = 0;
    }
    
    
    
    } catch (Exception e) {
    JOptionPane.showMessageDialog(null, "Erro!!!");
    }      
    }//GEN-LAST:event_tabelaMouseClicked

    private void butaoEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butaoEditarActionPerformed
    if(tfId.getText().equals("")){
        JOptionPane.showMessageDialog(this, "OPA!!!.", "USUARIO", 0,
        new ImageIcon(getClass().getResource("/imagem/OPA.png"))); 
        JOptionPane.showMessageDialog(this, "INFORME UMA LINHA NA TABELA.", "USUARIO", 0,
        new ImageIcon(getClass().getResource("/imagem/ATENCAO.png"))); 
        JOptionPane.showMessageDialog(this, "USUARIO NÃO SELECIONADO!.", "USUARIO", 0,
        new ImageIcon(getClass().getResource("/imagem/ERRO USUARIO.png"))); 
    }else{
    modelUsuario.setNome(tfLogin.getText());
    modelUsuario.setSenha(tfSenha.getText());
    modelUsuario.setTipo(jComboBox1.getSelectedItem()+"");
    
    modelUsuario.setAbandonar_venda(abandonar_venda);
    modelUsuario.setCadastro_bairro(cadastro_bairro);
    modelUsuario.setCadastro_cidade(cadastro_cidade);
    modelUsuario.setCadastro_cliente(cadastro_cliente);
    modelUsuario.setCadastro_departamento(cadastro_departamento);
    modelUsuario.setCadastro_estivas(cadastro_estiva);
    modelUsuario.setCadastro_estoque(cadastro_estoque);
    modelUsuario.setCadastro_fornecedor(cadastro_fornecedor);
    modelUsuario.setCadastro_rua(cadastro_rua);
    modelUsuario.setCadastro_usuario(cadastro_usuario);
    modelUsuario.setCancelar_venda(cancelar_venda);
    modelUsuario.setDar_desconto(dar_desconto);
    modelUsuario.setDespesa(despesa);
    modelUsuario.setFazer_sangria(fazer_sangria);
    modelUsuario.setPagar_conta(pagar_conta);
    modelUsuario.setParcela_venda(parcelar_venda);
    modelUsuario.setRelatorio_conta_pagaga(relatorio_conta_paga);
    modelUsuario.setRelatorio_entrada_estoque(relatorio_entrada_estoque);
    modelUsuario.setRelatorio_estoque(relatorio_estoque);
    modelUsuario.setRelatorio_parcelamento(relatorio_parcelamento);
    modelUsuario.setRelatorio_produto_maisVendido(relatorio_produto_maisVendidos);
    modelUsuario.setRelatorio_saida_estoque(relatorio_saida_estoque);
    modelUsuario.setRelatorio_turno(relatorio_turno);
    modelUsuario.setRelatorio_venda(relatorio_venda);
    modelUsuario.setRetira_estoque(retirar_estoque);
    modelUsuario.setTipo_conta(tipo_conta);
    
    modelUsuario.setTipo(jComboBox1.getSelectedItem()+"");
    if(controllerUsuario.alterarUsuarioController(modelUsuario)){
        JOptionPane.showMessageDialog(this, "Alterado com sucesso!!!.", "USUARIO", 0,
        new ImageIcon(getClass().getResource("/imagem/CERTO.png"))); 
        listando();
        limparCampos();
    }else{
        JOptionPane.showMessageDialog(null, "Erro!!!");
    }         
    }
    }//GEN-LAST:event_butaoEditarActionPerformed

    private void butaExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butaExcluirActionPerformed
    try {  
    int linha = tabela.getSelectedRow();
    int cod = (int) tabela.getValueAt(linha, 0);
    if(controllerUsuario.excluirUsuarioController(cod)){
    JOptionPane.showMessageDialog(null, "Excluído com sucesso!!!");
    listando();
    limparCampos();
    };
    } catch (Exception e) {
    JOptionPane.showMessageDialog(this, "OPA!!!.", "USUARIO", 0,
    new ImageIcon(getClass().getResource("/imagem/OPA.png"))); 
    JOptionPane.showMessageDialog(this, "INFORME UMA LINHA NA TABELA.", "USUARIO", 0,
    new ImageIcon(getClass().getResource("/imagem/ATENCAO.png"))); 
    JOptionPane.showMessageDialog(this, "USUARIO NÃO SELECIONADO!.", "USUARIO", 0,
    new ImageIcon(getClass().getResource("/imagem/ERRO USUARIO.png")));
    }
    }//GEN-LAST:event_butaExcluirActionPerformed

    private void jRDespesasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRDespesasMouseClicked
    if(despesa == 1)
    {
    despesa = 0;
    }else{
    despesa = 1;    
    }
    }//GEN-LAST:event_jRDespesasMouseClicked

    private void jRRelatorioTurnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRRelatorioTurnoMouseClicked
   
    }//GEN-LAST:event_jRRelatorioTurnoMouseClicked

    private void jRParcelarVendasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRParcelarVendasMouseClicked
//    if(parcelar_venda == 1)
//    {
//    parcelar_venda = 0;
//    }else{
//    parcelar_venda = 1;    
//    }
    }//GEN-LAST:event_jRParcelarVendasMouseClicked
   private void limparCampos(){
       tfLogin.setText("");
       tfSenha.setText("");
   }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewUsuarioPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewUsuarioPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewUsuarioPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewUsuarioPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewUsuarioPerfil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butaExcluir;
    private javax.swing.JButton butaoEditar;
    private javax.swing.JButton butaocadastro;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRAbandonarVendas;
    private javax.swing.JRadioButton jRCadastroBairros;
    private javax.swing.JRadioButton jRCadastroCidade;
    private javax.swing.JRadioButton jRCadastroCliente;
    private javax.swing.JRadioButton jRCadastroDepartamento;
    private javax.swing.JRadioButton jRCadastroFornecedor;
    private javax.swing.JRadioButton jRCadastroProdutoEstiva;
    private javax.swing.JRadioButton jRCadastroProdutoEstoque;
    private javax.swing.JRadioButton jRCadastroRuas;
    private javax.swing.JRadioButton jRCadastroTiposConta;
    private javax.swing.JRadioButton jRCadastroUsuario;
    private javax.swing.JRadioButton jRCancelarVendas;
    private javax.swing.JRadioButton jRDarDesconto;
    private javax.swing.JRadioButton jRDespesas;
    private javax.swing.JRadioButton jRFazerSangria;
    private javax.swing.JRadioButton jRPagarContas;
    private javax.swing.JRadioButton jRParcelarVendas;
    private javax.swing.JRadioButton jRRelatorioContaPaga;
    private javax.swing.JRadioButton jRRelatorioEntradaEstoque;
    private javax.swing.JRadioButton jRRelatorioEstoque;
    private javax.swing.JRadioButton jRRelatorioParcelamentos;
    private javax.swing.JRadioButton jRRelatorioProdutosMaisVendidos;
    private javax.swing.JRadioButton jRRelatorioSaidaEstoque;
    private javax.swing.JRadioButton jRRelatorioTurno;
    private javax.swing.JRadioButton jRRelatorioVendas;
    private javax.swing.JRadioButton jRRestirarProdutosEstoque;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela;
    private javax.swing.JLabel tfId;
    private javax.swing.JTextField tfLogin;
    private javax.swing.JPasswordField tfSenha;
    // End of variables declaration//GEN-END:variables
}
